version: "3.9"

services:
  userservice:
    build: ./UserService/UserService
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  orderservice:
    build: ./OrderService/OrderService
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - userservice
      - paymentservice

  paymentservice:
    build: ./PaymentService/PaymentService
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
